; resume.g
; called before a print from SD card is resumed
;
; generated by RepRapFirmware Configuration Tool v2 on Sat Mar 16 2019 23:24:38 GMT+0100 (Mitteleuropäische Normalzeit)


;;; NEED TO OVERWORK
